### ISSUE TITLE
dataloader NotImplementedError

### ISSUE THREAD

**Issue by funfwo** [williamFalcon/pytorch-lightning#489]
I want to use a changed GAN structure from the sample here with random samples of shape(3200,5). When run, NotImplementedError occurs. I dont see where the problem is. Thanks for help.

```
from argparse import ArgumentParser
from collections import OrderedDict
import torch
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader
import torch.nn as nn

lnum=torch.randn(1).item()*0.0001
print(lnum)

class ComeModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(ComeModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )

    def forward(self,x):
        out = self.model(x)
        return out

class GoModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(GoModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )
    def forward(self,x):
        out = self.model(x)
        return out

class TranscationModel(pl.LightningModule):
    def __init__(self,hparams):
        super(TranscationModel,self).__init__()
        self.hparams=hparams
        self.comer=ComeModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
        self.goer=GoModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
    def forward(self,x):
        chart_x = x[:3]
        fund_x = x[:]

        out =torch.log(1+self.comer(chart_x)+self.comer(fund_x))-torch.log(1+self.goer(chart_x)+self.goer(fund_x))
        return out

    def peak_loss(selfself,out,y):
        return F.binary_cross_entropy(out,y)

    def training_step(self, batch, batch_nb):
        x,y=batch
        y_pred=self.forward(x)
        ploss=self.peak_loss(y_pred,y)
        tqdm_dict={'ploss':ploss}
        output=OrderedDict(
            {
                'loss':ploss,
                'progress_bar':tqdm_dict,
                'log':tqdm_dict
            }
        )
        return output

    def configure_optimizers(self):
        lr =self.hparams.lr
        b1  = self.hparams.b1
        b2 = self.hparams.b2

        opt_come=torch.optim.Adam(self.comer.parameters(),lr=lr,betas=(b1,b2))
        opt_goer = torch.optim.Adam(self.comer.parameters(), lr=lr, betas=(b1, b2))
        return [opt_come,opt_goer],[]

    @pl.data_loader
    def train_dataloader(self):
        dataset = torch.randn(3200,5)
        print(dataset.size())
        return DataLoader(dataset,batch_size=self.hparams.batch_size)



def main(hparams):
    # ------------------------
    # 1 INIT LIGHTNING MODEL
    # ------------------------
    model = TranscationModel(hparams)

    # ------------------------
    # 2 INIT TRAINER
    # ------------------------
    trainer = pl.Trainer()

    # ------------------------
    # 3 START TRAINING
    # ------------------------
    trainer.fit(model)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument("--batch_size", type=int, default=64, help="size of the batches")
    parser.add_argument("--lr", type=float, default=0.0002, help="adam: learning rate")
    parser.add_argument("--b1", type=float, default=0.5,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--b2", type=float, default=0.999,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--in_fea", type=int, default=4,
                        help="dimensionality of the input dimension")
    parser.add_argument("--hid_dim", type=int, default=10,
                        help="dimensionality of the latent space")
    parser.add_argument("--out_fea", type=int, default=1,
                        help="dimensionality of the output dimension")

    hparams = parser.parse_args()

    main(hparams)

**Comment by funfwo** [comment]
from argparse import ArgumentParser
from collections import OrderedDict
import torch
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader
import torch.nn as nn

lnum=torch.randn(1).item()*0.0001
print(lnum)

class ComeModel(nn.Module):
def init(self,m_in,m_hid,m_out):
super(ComeModel,self).init()
self.model=nn.Sequential(
nn.Linear(m_in, m_hid),
nn.LeakyReLU(lnum,inplace=True),
nn.Linear(m_hid, m_out),
nn.LeakyReLU(lnum, inplace=True),
)

def forward(self,x):
    out = self.model(x)
    return out
class GoModel(nn.Module):
def init(self,m_in,m_hid,m_out):
super(GoModel,self).init()
self.model=nn.Sequential(
nn.Linear(m_in, m_hid),
nn.LeakyReLU(lnum,inplace=True),
nn.Linear(m_hid, m_out),
nn.LeakyReLU(lnum, inplace=True),
)
def forward(self,x):
out = self.model(x)
return out
class TranscationModel(pl.LightningModule):
def init(self,hparams):
super(TranscationModel,self).init()
self.hparams=hparams
self.comer=ComeModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
self.goer=GoModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
def forward(self,x):
chart_x = x[:3]
fund_x = x[:]

    out =torch.log(1+self.comer(chart_x)+self.comer(fund_x))-torch.log(1+self.goer(chart_x)+self.goer(fund_x))
    return out

def peak_loss(selfself,out,y):
    return F.binary_cross_entropy(out,y)

def training_step(self, batch, batch_nb):
    x,y=batch
    y_pred=self.forward(x)
    ploss=self.peak_loss(y_pred,y)
    tqdm_dict={'ploss':ploss}
    output=OrderedDict(
        {
            'loss':ploss,
            'progress_bar':tqdm_dict,
            'log':tqdm_dict
        }
    )
    return output

def configure_optimizers(self):
    lr =self.hparams.lr
    b1  = self.hparams.b1
    b2 = self.hparams.b2

    opt_come=torch.optim.Adam(self.comer.parameters(),lr=lr,betas=(b1,b2))
    opt_goer = torch.optim.Adam(self.comer.parameters(), lr=lr, betas=(b1, b2))
    return [opt_come,opt_goer],[]

@pl.data_loader
def train_dataloader(self):
    dataset = torch.randn(3200,5)
    print(dataset.size())
    return DataLoader(dataset,batch_size=self.hparams.batch_size)
def main(hparams):
# ------------------------
# 1 INIT LIGHTNING MODEL
# ------------------------
model = TranscationModel(hparams)

# ------------------------
# 2 INIT TRAINER
# ------------------------
trainer = pl.Trainer()

# ------------------------
# 3 START TRAINING
# ------------------------
trainer.fit(model)
if name == 'main':
parser = ArgumentParser()
parser.add_argument("--batch_size", type=int, default=64, help="size of the batches")
parser.add_argument("--lr", type=float, default=0.0002, help="adam: learning rate")
parser.add_argument("--b1", type=float, default=0.5,
help="adam: decay of first order momentum of gradient")
parser.add_argument("--b2", type=float, default=0.999,
help="adam: decay of first order momentum of gradient")
parser.add_argument("--in_fea", type=int, default=4,
help="dimensionality of the input dimension")
parser.add_argument("--hid_dim", type=int, default=10,
help="dimensionality of the latent space")
parser.add_argument("--out_fea", type=int, default=1,
help="dimensionality of the output dimension")

hparams = parser.parse_args()

main(hparams)

**Comment by funfwo** [comment]
The code is reorganized here.

from argparse import ArgumentParser
from collections import OrderedDict
import torch
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader
import torch.nn as nn

lnum=torch.randn(1).item()*0.0001
print(lnum)

class comeModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(comeModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )

    def forward(self,x):
        out = self.model(x)
        return out

class goModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(goModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )
    def forward(self,x):
        out = self.model(x)
        return out
class TranscationModel(pl.LightningModule):
    def __init__(self,hparams):
        super(TranscationModel,self).__init__()
        self.hparams=hparams
        self.comeer=comeModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
        self.goer=goModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
    def forward(self,x):
        chart_x = x[:3]
        fund_x = x[:]

        out =torch.log(1+self.comeer(chart_x)+self.comeer(fund_x))-torch.log(1+self.goer(chart_x)+self.goer(fund_x))
        return out

    def peak_loss(selfself,out,y):
        return F.binary_cross_entropy(out,y)

    def training_step(self, batch, batch_nb):
        x,y=batch
        y_pred=self.forward(x)
        ploss=self.peak_loss(y_pred,y)
        tqdm_dict={'ploss':ploss}
        output=OrderedDict(
            {
                'loss':ploss,
                'progress_bar':tqdm_dict,
                'log':tqdm_dict
            }
        )
        return output

    def configure_optimizers(self):
        lr =self.hparams.lr
        b1  = self.hparams.b1
        b2 = self.hparams.b2

        opt_come=torch.optim.Adam(self.comeer.parameters(),lr=lr,betas=(b1,b2))
        opt_goer = torch.optim.Adam(self.comeer.parameters(), lr=lr, betas=(b1, b2))
        return [opt_come,opt_goer],[]

    @pl.data_loader
    def train_dataloader(self):
        dataset = torch.randn(3200,5)
        print(dataset.size())
        return DataLoader(dataset,batch_size=self.hparams.batch_size)



def main(hparams):
    # ------------------------
    # 1 INIT LIGHTNING MODEL
    # ------------------------
    model = TranscationModel(hparams)

    # ------------------------
    # 2 INIT TRAINER
    # ------------------------
    trainer = pl.Trainer()

    # ------------------------
    # 3 START TRAINING
    # ------------------------
    trainer.fit(model)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument("--batch_size", type=int, default=64, help="size of the batches")
    parser.add_argument("--lr", type=float, default=0.0002, help="adam: learning rate")
    parser.add_argument("--b1", type=float, default=0.5,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--b2", type=float, default=0.999,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--in_fea", type=int, default=4,
                        help="dimensionality of the input dimension")
    parser.add_argument("--hid_dim", type=int, default=10,
                        help="dimensionality of the latent space")
    parser.add_argument("--out_fea", type=int, default=1,
                        help="dimensionality of the output dimension")

    hparams = parser.parse_args()

    main(hparams)

**Comment by funfwo** [comment]
I tried to reorganize the code, but failed.
The main part is similar. I want to train come model with some of the input and go model with the other. Transaction model use the output of the come and go and do loss function here.
Thanks.

**Comment by williamFalcon** [comment]
please share the stack trace.

**Comment by williamFalcon** [comment]
Looks like your code has a bunch of bugs. I fixed it for you

```python
from argparse import ArgumentParser
from collections import OrderedDict
import torch
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader
import torch.nn as nn

lnum=torch.randn(1).item()*0.0001
print(lnum)

class ComeModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(ComeModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )

    def forward(self,x):
        out = self.model(x)
        return out

class GoModel(nn.Module):
    def __init__(self,m_in,m_hid,m_out):
        super(GoModel,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(m_in, m_hid),
            nn.LeakyReLU(lnum,inplace=True),
            nn.Linear(m_hid, m_out),
            nn.LeakyReLU(lnum, inplace=True),
        )
    def forward(self,x):
        out = self.model(x)
        return out

class TranscationModel(pl.LightningModule):
    def __init__(self,hparams):
        super(TranscationModel,self).__init__()
        self.hparams=hparams
        self.comer=ComeModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
        self.goer=GoModel(self.hparams.in_fea,self.hparams.hid_dim,self.hparams.out_fea)
    def forward(self,x):
        chart_x = x[:3]
        fund_x = x[:]

        a = self.comer(chart_x)
        b = self.comer(fund_x)
        c = self.goer(chart_x)
        d = self.goer(fund_x)
        print(a.shape, b.shape, c.shape, d.shape)


        out = torch.log(1+a+b)-torch.log(1+c+d)
        return out

    def peak_loss(selfself,out,y):
        return F.binary_cross_entropy(out,y)

    def training_step(self, batch, batch_nb, optimizer_index):
        x=batch
        y_pred=self.forward(x)
        ploss=self.peak_loss(y_pred,y)
        tqdm_dict={'ploss':ploss}
        output=OrderedDict(
            {
                'loss':ploss,
                'progress_bar':tqdm_dict,
                'log':tqdm_dict
            }
        )
        return output

    def configure_optimizers(self):
        lr =self.hparams.lr
        b1  = self.hparams.b1
        b2 = self.hparams.b2

        opt_come=torch.optim.Adam(self.comer.parameters(),lr=lr,betas=(b1,b2))
        opt_goer = torch.optim.Adam(self.comer.parameters(), lr=lr, betas=(b1, b2))
        return [opt_come,opt_goer],[]

    @pl.data_loader
    def train_dataloader(self):
        dataset = torch.randn(3200,5)
        print(dataset.size())
        return DataLoader(dataset,batch_size=self.hparams.batch_size)



def main(hparams):
    # ------------------------
    # 1 INIT LIGHTNING MODEL
    # ------------------------
    model = TranscationModel(hparams)

    # ------------------------
    # 2 INIT TRAINER
    # ------------------------
    trainer = pl.Trainer()

    # ------------------------
    # 3 START TRAINING
    # ------------------------
    trainer.fit(model)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument("--batch_size", type=int, default=64, help="size of the batches")
    parser.add_argument("--lr", type=float, default=0.0002, help="adam: learning rate")
    parser.add_argument("--b1", type=float, default=0.5,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--b2", type=float, default=0.999,
                        help="adam: decay of first order momentum of gradient")
    parser.add_argument("--in_fea", type=int, default=5,
                        help="dimensionality of the input dimension")
    parser.add_argument("--hid_dim", type=int, default=10,
                        help="dimensionality of the latent space")
    parser.add_argument("--out_fea", type=int, default=1,
                        help="dimensionality of the output dimension")

    hparams = parser.parse_args()

    main(hparams)
```

but there is still a bug with dimensions in the loss. I don't know what you're trying to do, so I can't spend time fixing it right now, the dimensions of a,b,c,d don't match and the log loss fails.

But your data are fine.

**Comment by funfwo** [comment]
Thanks for your help
Traceback (most recent call last):
  File "D:/stockanalysis/buysellprice/simple.py", line 127, in <module>
    main(hparams)
gpu available: True, used: False
  File "D:/stockanalysis/buysellprice/simple.py", line 107, in main
    trainer.fit(model)
  File "D:\stockanalysis\venv\lib\site-packages\pytorch_lightning\models\trainer.py", line 507, in fit
    self.__run_pretrain_routine(model)
  File "D:\stockanalysis\venv\lib\site-packages\pytorch_lightning\models\trainer.py", line 672, in __run_pretrain_routine
    self.get_dataloaders(ref_model)
  File "D:\stockanalysis\venv\lib\site-packages\pytorch_lightning\models\trainer.py", line 441, in get_dataloaders
    self.tng_dataloader = model.tng_dataloader
  File "D:\stockanalysis\venv\lib\site-packages\pytorch_lightning\root_module\decorators.py", line 14, in _data_loader
    setattr(self, attr_name, fn(self))
  File "D:\stockanalysis\venv\lib\site-packages\pytorch_lightning\root_module\root_module.py", line 73, in tng_dataloader
    raise NotImplementedError
NotImplementedError
this is what pycharm shows me when running. The same as what I encountered at first.
I focus my problem into two facets.First, what is the dataloader mechanism of your package. I check the source code tngloader is depreciated, but train_dataloader doesn't work. 
The second is do hoping to have a full documentation for the parameters flow of your package.
I renewed my model yesterday and run well in plain pytorch. But I deeply wanted to transfer to lightning due to its ease for further implementation. 

I cannot preview my reply. so sorry for the poor indentation of the traceback.

**Comment by funfwo** [comment]
plus, I am doing multitask learning. Perhaps lightning can provide a template for such scenario.

**Comment by williamFalcon** [comment]
@funfwo did you fix your issue? can reopen if needed. 
Can you send a multitask learning demo or add a template? would be a great contribution :)

**Comment by funfwo** [comment]
The problem still exists. I downgrade my model in plain pytorch. it's a prototype.

**Comment by djstrong** [comment]
Multitask learning example would be great.
